version: '3.1'

services:
  app:
    restart: always
    build: .
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/app
      - JDBC_DATABASE_USERNAME=app
      - JDBC_DATABASE_PASSWORD=app
    depends_on:
      - db
  db:
    restart: always
    image: postgres:13-alpine
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app

volumes:
  data: